{
    'name' : 'Bhuarjan',
    'version': '18.0',

    'summary': 'BhoomiArjan — Land Acquisition Management System.',
    'sequence':'-1',
    'description':'To digitize and streamline the end-to-end workflow for land acquisition under RFCTLARR Act, 2013, from Form-10 initiation to Section 19 declaration, ensuring transparency, traceability, and accountability at each level.',
    'category':'Bhumuarjan',
    'website': 'bhuarjan.com',
    'depends':['mail'],
    'data':[
        'data/ir_sequence_data.xml',
        # 'data/department_data.xml',
        # 'data/chhattisgarh_districts_data.xml',
        # 'data/chhattisgarh_tehsils_data.xml',
        # 'data/chhattisgarh_villages_data.xml',
        'security/ir.model.access.csv',
        'security/secrurity.xml',
        'reports/form10_survey_report.xml',
        'views/district_views.xml',
        'views/bhu_sub_division_views.xml',
        'views/bhu_tehsil_views.xml',
        'views/bhu_circle_views.xml',
        'views/bhu_village_views.xml',
        'views/project_views.xml',
        'views/res_users.xml',
        'views/master_views.xml',
        'views/landowner_views.xml',
        'views/survey_views.xml',
        'views/menuitem.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',

}