{
    'name' : 'Bhuarjan',
    'version': '18.0.1.1.0',
    'summary': 'BhoomiArjan — Land Acquisition Management System.',
    'sequence':'-1',
    'description':'To digitize and streamline the end-to-end workflow for land acquisition under RFCTLARR Act, 2013, from Form-10 initiation to Section 19 declaration, ensuring transparency, traceability, and accountability at each level.',
    'category':'Bhumuarjan',
    'website': 'bhuarjan.com',
    'depends':['website','mail',  'hr_org_chart', 'auth_oauth'],
    'data':[
        'data/ir_sequence_data.xml',
        'data/ir_model_access_data.xml',
        'security/ir.model.access.csv',
        'data/land_type_data.xml',
        'data/tree_master_data.xml',
        'data/tree_rate_master_data.xml',
        'data/photo_type_master_data.xml',
        # District and Sub-Division data - commented out to prevent import
        # 'data/chhattisgarh_districts_data.xml',
        # 'data/raigarh_sub_division_data.xml',
        # 'data/raipur_sub_division_data.xml',
        # 'data/tehsil_data.xml',
        # Village data - commented out to prevent import
        # 'data/raigarh_village_data.xml',
        'data/department_data.xml',
        'data/settings_master_data.xml',
        # Process-related sample data - commented out to prevent default import
        'data/sample_project_data.xml',
        'data/sample_sequence_settings.xml',
        # 'data/sample_expert_committee_report.xml',
        # 'data/sample_landowners.xml',  # Disabled - not importing sample landowners
        # 'data/sample_surveys.xml',  # Disabled - not importing sample surveys
        # 'data/sample_section4_config.xml',
        # 'data/sample_section4_notifications.xml',
        # 'data/sample_section15_objections.xml',  # Disabled - not importing objection data
        # 'data/sample_section11_reports.xml',
        # 'data/sample_section19_notifications.xml',  # Disabled - not importing Section 19 notifications by default
        'data/kharsiyan_rate_master_data.xml',
        'data/section_master_data.xml',
        'data/qweb_report_paper_format.xml',
        'security/secrurity.xml',
        'reports/report_common_styles.xml',
        'reports/form10_bulk_table_report.xml',
        'reports/award_letter_report.xml',
        'reports/section4_notification_report.xml',
        'reports/section11_preliminary_report.xml',
        'reports/section19_notification_report.xml',
        'reports/section21_notification_report.xml',
        'reports/document_template_pdf_report.xml',
        'reports/draft_award_report.xml',
        'reports/sia_order_report.xml',
        'reports/sia_proposal_report.xml',
        'reports/expert_committee_proposal_report.xml',
        'reports/expert_committee_order_report.xml',
        'reports/section15_objection_resolution_report.xml',
        'reports/section23_award_report.xml',
        'reports/project_master_report.xml',
        'views/district_views.xml',
        'views/bhu_sub_division_views.xml',
        'views/bhu_tehsil_views.xml',
        'views/bhu_village_views.xml',
        'views/res_users_views.xml',
        'views/project_views.xml',
        'views/master_views.xml',
        'views/landowner_views.xml',
        'views/survey_views.xml',
        'views/survey_bulk_approval_wizard_views.xml',
        'views/document_vault_views.xml',
        'views/sia_team_views.xml',
        'views/sia_team_member_views.xml',
        'wizard/sia_send_back_wizard.xml',
        'wizard/sia_download_wizard_views.xml',
        'wizard/process_send_back_wizard.xml',
        'wizard/section8_approve_reject_wizard.xml',
        'wizard/reject_survey_wizard_views.xml',
        'views/section15_objection_views.xml',
        'views/process_stub_views.xml',
        'views/process_views.xml',
        'views/section4_notification_views.xml',
        'views/section11_preliminary_report_views.xml',
        'views/section19_notification_views.xml',
        'views/section21_notification_views.xml',
        'views/section18_rr_scheme_views.xml',
        'views/section8_views.xml',
        'views/section23_award_views.xml',
        # 'views/section23_award_survey_line_views.xml',  # Uncomment after first update to register model
        'views/all_section_report_views.xml',
        'views/process_report_views.xml',
        'views/draft_award_views.xml',
        'views/dashboard_views.xml',
        'views/expert_committee_report_views.xml',
        'views/message_wizard_views.xml',
        'views/company_switcher_views.xml',
        'views/post_award_payment_views.xml',
        'views/payment_reconciliation_views.xml',
        'views/payment_file_views.xml',
        'views/payment_reconciliation_bank_views.xml',
        'views/land_rate_master_views.xml',
        'views/tree_master_views.xml',
        'views/tree_rate_master_views.xml',
        'views/award_simulator_views.xml',
        'views/law_master_views.xml',
        'views/section_master_views.xml',
        'views/section20a_railways_views.xml',
        'views/section20d_railways_views.xml',
        'views/section20e_railways_views.xml',
        'views/section3a_nh_views.xml',
        'views/section3c_nh_views.xml',
        'views/section3d_nh_views.xml',
        'views/mutual_consent_policy_views.xml',
        'views/photo_type_master_views.xml',
        'views/settings_master_views.xml',
        'views/channel_master_views.xml',
        'views/document_template_master_views.xml',
        'views/jwt_token_views.xml',
        'views/mobile_otp_views.xml',
        'views/app_version_views.xml',
        'views/api_docs_views.xml',
        'wizard/report_wizard.xml',
        'wizard/user_report_wizard.xml',
        'views/qr_microsite_templates.xml',
        'data/mail_data.xml',
        'views/menu_root.xml',
        'views/group_dashboard_views.xml',
        'views/menuitem.xml',
        'views/issue_views.xml',
        'views/login_templates.xml',
        'views/layout_templates.xml',
        # Debranding views (merged from debrand_odoo module)
        'views/debrand_views.xml',
        # Password eyes icon views (merged from password_eyes_icon module)
        'views/password_eyes_templates.xml',
        # Widget Owl (merged from widget_owl module)
        'views/widget_owl_res_partner.xml',


    ],
    'assets': {
        'web.assets_backend': [
            # 'bhuarjan/static/src/xml/mail_systray_hide_button.xml',
            # 'bhuarjan/static/src/css/rate_master_form.css',
            'bhuarjan/static/src/css/survey_status.css',
            'bhuarjan/static/src/css/search_view.css',
            'bhuarjan/static/src/css/dashboard.css',
            # Dashboard files - organized in separate folders
            'bhuarjan/static/src/dashboard/css/admin_dashboard.css',
            'bhuarjan/static/src/dashboard/xml/dashboard_header.xml',
            'bhuarjan/static/src/dashboard/xml/admin_dashboard.xml',
            'bhuarjan/static/src/dashboard/js/web_client_dashboard.js',
            # Unified Dashboard (replaces separate JS files)
            'bhuarjan/static/src/dashboard/js/unified_dashboard.js',
            # SDM Dashboard files (CSS and XML only - JS is in unified_dashboard.js)
            'bhuarjan/static/src/dashboard/css/sdm_dashboard.css',
            'bhuarjan/static/src/dashboard/xml/sdm_dashboard.xml',
            # Department User Dashboard files (XML only - JS is in unified_dashboard.js)
            'bhuarjan/static/src/dashboard/xml/department_dashboard.xml',
            # Collector Dashboard XML (JS is shared with SDM)
            'bhuarjan/static/src/dashboard/xml/collector_dashboard.xml',
            # District Admin Dashboard XML (JS is in unified_dashboard.js)
            'bhuarjan/static/src/dashboard/xml/district_dashboard.xml',
            # Group Dashboard (for Administrators)
            'bhuarjan/static/src/dashboard/css/group_dashboard.css',
            'bhuarjan/static/src/dashboard/xml/group_dashboard.xml',
            'bhuarjan/static/src/dashboard/js/group_dashboard.js',
            # Role-based Dashboard (routes to appropriate dashboard based on user role)
            'bhuarjan/static/src/dashboard/js/role_based_dashboard.js',

            # 'bhuarjan/static/src/css/landowner_documents.css',
            'bhuarjan/static/src/scss/hierarchy_view.scss',
            # 'bhuarjan/static/src/scss/organization_chart.scss',
            # 'bhuarjan/static/src/js/hierarchy_expand.js',
            # 'bhuarjan/static/src/js/survey_form_confirm.js',
            'bhuarjan/static/src/js/support_issue.js',
            # Debranding assets (merged from debrand_odoo module)
            'bhuarjan/static/src/js/debrand_user_menu.js',
            'bhuarjan/static/src/xml/debrand_web.xml',
            # Password eyes icon assets (merged from password_eyes_icon module)
            'bhuarjan/static/src/scss/password_eyes_icon.scss',
            'bhuarjan/static/src/js/password_eyes_icon.js',
            'bhuarjan/static/src/js/password_eyes_icon_field.js',
            'bhuarjan/static/src/xml/password_eyes_icon.xml',
            # Timepicker assets (merged from timepicker module)
            'bhuarjan/static/src/xml/timepicker.xml',
            'bhuarjan/static/src/css/timepicker.css',
            'bhuarjan/static/src/js/timepicker.js',
            # Widget Owl (merged from widget_owl module)
            'bhuarjan/static/src/js/components/list_renderer.js',
            'bhuarjan/static/src/js/components/one2many_field_dialoge.js',
            'bhuarjan/static/src/js/components/popup.js',
            # Image Capture Widget (merged from image_capture_upload_widget module)
            # 'bhuarjan/static/src/scss/image_capture.scss',
            # 'bhuarjan/static/src/js/components/image_capture.js',
            # 'bhuarjan/static/src/xml/image_capture_templates.xml',
            'bhuarjan/static/src/scss/image_capture.scss',
            'bhuarjan/static/src/js/components/image_capture.js',
            'bhuarjan/static/src/xml/image_capture_templates.xml',
            # Project Timeline Widget
            'bhuarjan/static/src/scss/project_timeline.scss',
            'bhuarjan/static/src/js/components/project_timeline.js',
            'bhuarjan/static/src/js/components/project_timeline.js',
            'bhuarjan/static/src/xml/project_timeline.xml',
            # KML Viewer Component
            'bhuarjan/static/src/components/kml_viewer/kml_viewer.js',
            'bhuarjan/static/src/components/kml_viewer/kml_viewer.xml',
        ],
        'web.assets_frontend': [
            'bhuarjan/static/src/scss/password_eyes_icon.scss',
            'bhuarjan/static/src/js/password_toggle_public.js',
        ],
        'web.assets_public': [
            'bhuarjan/static/src/scss/password_eyes_icon.scss',
            'bhuarjan/static/src/js/password_toggle_public.js',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',

}
